### ISSUE TITLE
My PRs is in Review

### ISSUE THREAD

**Issue by barawalojas** [abhishekdoifode1/Hacktoberfest2020#253]
Hello there,
I'm having a review session on my PR's in Hacktoberfest Contributions saying mature in 12 days.
So, **I want to ask that after 12 days or 13 days, the day comes is 2nd November,
till that time, the PR's I've submitted will be valid or not..?**

**Comment by barawalojas** [comment]
Review in Contributions
![image](https://user-images.githubusercontent.com/58108638/96676854-f8c56500-138b-11eb-90b6-95ee0a5aca24.png)

**Comment by barawalojas** [comment]
@abhishekdoifode1 
Can you please tell me what is that...

**Comment by Deepu2002d** [comment]
Same problem I am facing. 
I submitted 3 PR today and it's showing 13 days needed to review and 13 days later there will be September. So, now what?
